# name space
/robot_arm_4DOF:
    # based on https://wiki.ros.org/ros_control this controller reads the state 
    # of all the joints
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    joint1_controller:
        #this controller recieves position and via PID it takes care of the effort
        # needed to move the joint. based on https://wiki.ros.org/ros_control
        # type: position_controllers/JointPositionController
        #type: velocity_controllers/JointVelocityController
        type: position_controllers/JointPositionController
        joint: joint_1
        pid: {p: 10.0, i: 0.1, d: 0.1}

    joint2_controller:
        type: position_controllers/JointPositionController
        joint: joint_2
        pid: {p: 10.0, i: 0.1, d: 0.1}

    joint2_controller:
        type: position_controllers/JointPositionController
        joint: joint_3
        pid: {p: 10.0, i: 0.1, d: 0.1}

    joint2_controller:
        type: position_controllers/JointPositionController
        joint: joint_4
        pid: {p: 10.0, i: 0.1, d: 0.1}

    joint2_controller:
        type: position_controllers/JointPositionController
        joint: joint_51
        pid: {p: 10.0, i: 0.1, d: 0.1}

    joint2_controller:
        type: position_controllers/JointPositionController
        joint: joint_52
        pid: {p: 10.0, i: 0.1, d: 0.1}